# Generated by Django 4.0.6 on 2022-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200, verbose_name='desc')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imag')),
                ('Patente', models.CharField(max_length=6, verbose_name='paten')),
            ],
        ),
    ]
