# Generated by Django 4.0.6 on 2022-07-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_rename_id_atencion_patente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='patente',
            new_name='id',
        ),
    ]
