# Generated by Django 4.0.6 on 2022-07-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_rename_patente_atencion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
