# Generated by Django 4.0.6 on 2022-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='marca',
            field=models.CharField(default='sin marca', max_length=50),
        ),
        migrations.AddField(
            model_name='atencion',
            name='modelo',
            field=models.CharField(default='sin modelo', max_length=50),
        ),
    ]
