# Generated by Django 4.0.6 on 2022-07-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_atencion_marca_atencion_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='marca',
            field=models.CharField(default='sin marca', max_length=50, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='modelo',
            field=models.CharField(default='sin modelo', max_length=50, verbose_name='modelo'),
        ),
    ]
