# Generated by Django 4.0.6 on 2022-07-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_alter_atencion_marca_alter_atencion_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='Descripcion',
            field=models.CharField(max_length=200, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='Patente',
            field=models.CharField(max_length=6, verbose_name='patente'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='modelo'),
        ),
    ]
