# Generated by Django 4.0.6 on 2022-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_remove_atencion_marca_remove_atencion_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
