# Generated by Django 4.0.6 on 2022-07-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_mecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='rut',
            field=models.CharField(max_length=20, verbose_name='rut'),
        ),
    ]
